apiVersion: v1
kind: Pod
metadata:
  name: java-web-service-pod-1
spec:
  nodeName: kind-cluster-worker
  containers:
  - name: java-web-service-container
    image: docker.io/nagabhushanamn/java-web-service:npci
    volumeMounts:
    - name: vol1
      mountPath: /app/log
  - name: log-reader-container
    image: busybox
    command: ['sleep', '3600']
    volumeMounts:
    - name: vol1
      mountPath: /var/log
  volumes:
  - name: vol1
    hostPath: 
     path: /var/log
     type: DirectoryOrCreate
  
---
