apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-web-service
  template:
    metadata:
      labels:
        app: java-web-service
    spec:
      containers:
      - name: java-web-service-container
        image: docker.io/nagabhushanamn/java-web-service:batch7
        volumeMounts:
        - name: vol1
          mountPath: /app/log

      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: nfs-pvc
    

